# Uncomment this line to define a global platform for your project
platform :osx, '10.9'

target 'SalesforceScripting' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'ZKSforce'
  #pod 'Sparkle', '~> 1.15.1'
end

target 'SforceTests' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for SforceTests
  pod 'ZKSforce'
  #  pod 'Sparkle', '~> 1.15.1'
end
